# Implementation of QR algorithm from scratch and compare with built_in numpy funtion

In [1]:
import numpy as np

In [2]:
a1=np.array([8,3,4])
a2=np.array([1,5,9])
a3=np.array([6,7,2])

In [3]:
"""
a1=np.array([8,1,6])
a2=np.array([3,5,7])
a3=np.array([4,9,2])
"""

'\na1=np.array([8,1,6])\na2=np.array([3,5,7])\na3=np.array([4,9,2])\n'

In [4]:
r_manual=np.zeros((3,3))

***Manual Computation of QR algorithm:***

In [5]:
q1=a1/np.linalg.norm(a1)
print(q1)

r_manual[0,0]=np.linalg.norm(a1)
r_manual[0,1]=q1.T@a2

q2=a2-(q1.T@a2)*q1

r_manual[1,1]=np.linalg.norm(q2)

q2=q2/np.linalg.norm(q2)
print(q2)


q3=a3-(q1.T@a3)*q1-(q2.T@a3)*q2

r_manual[0,2]=q1.T@a3
r_manual[1,2]=q2.T@a3
r_manual[2,2]=np.linalg.norm(q3)

q3=q3/np.linalg.norm(q3)
print(q3)




[0.8479983  0.31799936 0.42399915]
[-0.52229204  0.36546806  0.77048304]
[-0.09005497  0.8748197  -0.47600483]


***Checking orthogonality and Orthonormality***

In [6]:
print(np.linalg.norm(q1),np.linalg.norm(q2),np.linalg.norm(q3))

1.0 1.0 0.9999999999999998


In [7]:
print(q1@q2,q1@q3,q2@q3)

-1.6653345369377348e-16 -2.220446049250313e-16 2.220446049250313e-16


***Calling QR algoritm from the numpy package:***

In [8]:
matrix1=np.array([[8,1,6],[3,5,7],[4,9,2]])
print(matrix1)

[[8 1 6]
 [3 5 7]
 [4 9 2]]


In [9]:
q, r = np.linalg.qr(matrix1) 

print('\nq[0]:\n', q[:,0]) 
print('\nq[1]:\n', q[:,1]) 
print('\nq[2]:\n', q[:,2]) 


q[0]:
 [-0.8479983  -0.31799936 -0.42399915]

q[1]:
 [ 0.52229204 -0.36546806 -0.77048304]

q[2]:
 [ 0.09005497 -0.8748197   0.47600483]


For manulal computations:

In [10]:

print('\nq[0]:\n', q1) 
print('\nq[1]:\n', q2) 
print('\nq[2]:\n', q3) 


q[0]:
 [0.8479983  0.31799936 0.42399915]

q[1]:
 [-0.52229204  0.36546806  0.77048304]

q[2]:
 [-0.09005497  0.8748197  -0.47600483]


In [11]:
print(r)

[[-9.43398113 -6.25398749 -8.16198368]
 [ 0.         -8.23939564 -0.96549025]
 [ 0.          0.         -4.63139839]]


In [12]:
print(r_manual)

[[9.43398113 6.25398749 8.16198368]
 [0.         8.23939564 0.96549025]
 [0.         0.         4.63139839]]


***QR decomposition is unique.***

---

